print("HY HOW ARE U???" , "I AM FINE")
print("I AM FINE TOO")
print("What is your age?")
print(18)
print("I am 18 years old")  
print("What is your name?")
print("My name is John")
print("Enter your age: ")
age = input()
print("You entered age:", age)
print("Enter your name: ")
name = input()
print("You entered name:", name)
print("Hello", name, "you are", age, "years old.")
print("Thank you for sharing your details!")
